유저, 피드, 댓글, 대댓글 엔티티 구현
DevTraces/BackEnd pull request #4
Opened 2023-02-05 14:19 UTC by DongvinPark

## 📍 관련 이슈
- #3 

## 📍 특이사항
- 코드 구현 의도 : 유저 엔티티가 피드, 댓글, 대댓글 엔티티와 모두 1:N 관계를 가지도록 엔티티를 설계했습니다. 그래야 특정 유저가 자기 프로필 사진을 바꿨을 때, 그 유저가 작성한 피드,댓글,대댓글에서 변경된 프사가 동시에 참조되어 프런트엔드로 전달될 수 있기 때문입니다.
- User.java 라고 네이밍하고 싶었지만, 이 경우 JPA에서 피드,댓글,대댓글 엔티티와의 1:N 매핑관계를 전혀 잡아내지를 못해서 일단 UserEntity.java라고 네이밍 하자 정상적으로 1:N 관계가 설정되었습니다.
- BaseEntity와 UserSignUpType, UserStatusType의 위치와 관련 패키지 설정에 대한 논의가 필요해 보입니다.
- 기능완료 테스트 이미지 : 1번 유저가 피드를 올리고, 2번 유저가 거기에 댓글을 달고, 1번 유저가 다시 대댓글을 달아 놓은 상태에서, 1번 유저와 2번 유저가 모두 자기 프사를 변경했을 때, 이미 작성해 놓은 피드,댓글,대댓글에서도 변경된 프사 링크 스트링이 반영되는지를 테스트 했습니다. 테스트 결과 변경이 반영되는 것을 확있했고 이미지로 남갑니다.
![A7BF06AC-8850-4D13-B0A3-1BE9F06EB1EA](https://user-images.githubusercontent.com/99060708/216824679-3a2e134d-1a5d-45ab-9ff6-5a3d66b38f78.jpeg)

## 📍 테스트
- [x] API Test
- [ ] 단위 테스트 : 엘라스틱 서치와 연계 필요.

2023-02-05 16:48 UTC, soeunkk requested changes
댓글로 제안을 너무 많이 드린 것 같아 죄송하네요..ㅎㅎ
개인적으로는 커밋 단위가 조금 큰 것 같습니다! 유저, 피드, 댓글, 대댓글 각각 따로 올리셔도 괜찮았을 것 같아요!
너무너무 수고 많으셨습니다. 👏👏

2023-02-05 16:48 UTC, soeunkk commented on src/main/java/com/devtraces/arterest/domain/Feed.java
> +    private UserEntity userEntity;
작성자의 정보(authorId, authorNickname)는 45줄에 작성해주신 userEntity로 얻을 수 있을 것 같습니다. 
userEntity 대신 author이라고 네이밍하고 authorId, authorNickname 필드를 빼는 건 어떨까요?

2023-02-05 16:48 UTC, soeunkk commented on src/main/java/com/devtraces/arterest/domain/UserEntity.java
> +public class UserEntity extends BaseEntity {
컨벤션에 따르면 엔티티 클래스명에서 "Entity" 어미는 빼기로 했기 때문에 User로 수정하는 것이 좋을 것 같습니다.
(만약 h2 데이터베이스의 예약어 때문에 User 키워드를 사용하실 수 없는 거라면 배포 환경과 동일하게 하기 위해 h2 대신 local mysql 계정을 연결하시는 건 어떨까요?)

2023-02-05 16:48 UTC, soeunkk commented on src/main/java/com/devtraces/arterest/domain/UserEntity.java
> +    private String password; //암호화 팔요.
주석에 오타가 있는 것 같습니다 :)

2023-02-05 16:48 UTC, soeunkk commented on src/main/java/com/devtraces/arterest/domain/Reply.java
> +    private UserEntity user;
위와 마찬가지로 user 대신 author로 네이밍하고 authorId 필드를 제거해도 좋을 것 같습니다!

2023-02-05 16:48 UTC, soeunkk commented on src/main/java/com/devtraces/arterest/domain/Rereply.java
> +@AllArgsConstructor
이 부분도 마찬가지로 @Entity 위치 변경, @Setter 제거, @Table 생략, @NoArgsConstructor access 제한 및 위치 변경에 대해 제안드려봅니다!

2023-02-05 16:48 UTC, soeunkk commented on src/main/java/com/devtraces/arterest/domain/Rereply.java
> +    private UserEntity user;
user 대신 author로 네이밍하고 authorId 필드를 제거해도 좋을 것 같습니다!
그리고 rereply와 reply는 연관관계 매핑을 하지 않아도 괜찮을까요~?

2023-02-05 16:48 UTC, soeunkk commented on src/main/java/com/devtraces/arterest/domain/UserEntity.java
> +@AllArgsConstructor
이 부분도 마찬가지로 @Entity 위치 변경, @Setter 제거, @Table 생략, @NoArgsConstructor access 제한 및 위치 변경에 대해 제안드려봅니다!

2023-02-05 16:48 UTC, soeunkk commented on src/main/java/com/devtraces/arterest/domain/Feed.java
> +@Table(name = "feed_entity")
다른 클래스에도 @Table을 명시해주셨던데 혹시 명시하신 이유가 있으시다면 생략 대신 위치만 @Entity 근처로 이동해도 좋을 것 같아요~

2023-02-05 16:48 UTC, soeunkk commented on src/main/java/com/devtraces/arterest/domain/Reply.java
> +@AllArgsConstructor
이 부분도 마찬가지로 @entity 위치 변경, @Setter 제거, @table 생략, @NoArgsConstructor access 제한 및 위치 변경에 대해 제안드려봅니다!

2023-02-05 16:48 UTC, soeunkk commented on src/main/java/com/devtraces/arterest/domain/Reply.java
> +    private UserEntity user;
reply와 feed는 연관관계 매핑을 하지 않아도 괜찮을까요~? (매핑한다면 feedId 필드도 제거하면 좋을 것 같습니다)

2023-02-05 16:48 UTC, soeunkk commented on src/main/java/com/devtraces/arterest/domain/Feed.java
> +package com.devtraces.arterest.domain;
domain 내에서도 엔티티 별로 feed, reply, rereply, user 패키지를 만들고 안에 파일을 넣는 방식으로 하기로 했던 것 같습니다! 패키지 구조 조금만 수정해주시면 좋을 것 같아요ㅎㅎ

2023-02-05 16:58 UTC, soeunkk commented on src/main/java/com/devtraces/arterest/domain/Feed.java
> +    private UserEntity userEntity;
그리고 게시글에서 댓글과 연관관계 매핑이 필요할 듯 싶습니다!

2023-02-05 16:58 UTC, soeunkk commented on src/main/java/com/devtraces/arterest/domain/Feed.java
> +    private UserEntity userEntity;
그리고 게시글에서 댓글과 연관관계 매핑이 필요할 듯 싶습니다!

2023-02-05 17:01 UTC, soeunkk commented on src/main/java/com/devtraces/arterest/domain/Reply.java
> +    private UserEntity user;
그리고 댓글에서 대댓글과 연관관계 매핑이 필요할 듯 싶습니다!

2023-02-06 02:41 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/common/BaseEntity.java
> +public class BaseEntity {
common 내에 domain을 만들어야겠네요

2023-02-06 02:43 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/Feed.java
> +@Setter
게시물 수정 기능 같이 여러 필드를 한번에 수정해야 될 경우 Setter 어노테이션이 필요할 것 같아서 일단 추가해두었는데, 다른 팀원분들과 같이 얘기해보는 것이 좋을 것 같습니다.

2023-02-06 02:44 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/Feed.java
> +@Table(name = "feed_entity")
1:N 매핑 때문에 넣은 것인데, 로컬 Mysql에서 테스트 해보고 필요 없으면 빼겠습니다.

2023-02-06 02:45 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/Feed.java
> +@NoArgsConstructor
이 부분은 습관적으로 쓰다보니 깜빡했네요 ㄷㄷ

2023-02-06 02:45 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/Feed.java
> +@Entity
위치를 바꾸겠습니다.

2023-02-06 02:47 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/Rereply.java
> +@AllArgsConstructor
Entity 어노테이션은 위치를 바꾸고, 테이블 어노테이션은 Mysql 테스트 후 결정하고, Setter 어노테이션은 다른 팀원 분들의 의견도 들어본 후 결정하면 될 것 같습니다.

2023-02-06 02:47 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/Rereply.java
> +    private UserEntity user;
저도 그렇게 생각합니다 :)

2023-02-06 02:47 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/UserEntity.java
> +@AllArgsConstructor
Entity 어노테이션은 위치를 바꾸고, 테이블 어노테이션은 Mysql 테스트 후 결정하고, Setter 어노테이션은 다른 팀원 분들의 의견도 들어본 후 결정하면 될 것 같습니다.

2023-02-06 02:48 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/Reply.java
> +@AllArgsConstructor
Entity 어노테이션은 위치를 바꾸고, 테이블 어노테이션은 Mysql 테스트 후 결정하고, Setter 어노테이션은 다른 팀원 분들의 의견도 들어본 후 결정하면 될 것 같습니다.

2023-02-06 02:48 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/Feed.java
> +package com.devtraces.arterest.domain;
domain 내에서도 종류별로 구분하는 패키지를 새로 만들겠습니다.

2023-02-06 03:49 UTC, heyazoo1007 reviewed
저도 리뷰 남겼습니다!

2023-02-06 03:49 UTC, heyazoo1007 commented on src/main/java/com/devtraces/arterest/domain/Rereply.java
> +@AllArgsConstructor
객체 수정은 최대한 닫아두는 거에 동의합니다. 소은님이 말씀하신 @Setter 대신 메서드로 객체 정보를 변경할 수 있게 하는게 좋을 것 같습니다!

2023-02-06 03:49 UTC, heyazoo1007 commented on src/main/java/com/devtraces/arterest/domain/UserEntity.java
> +@AllArgsConstructor
Setter 어노테이션 관련해서 위에 댓글 남겼습니다!

2023-02-06 03:49 UTC, heyazoo1007 commented on src/main/java/com/devtraces/arterest/domain/UserEntity.java
> +public class UserEntity extends BaseEntity {
저도 소은님 의견에 동의합니다!

2023-02-06 03:49 UTC, heyazoo1007 commented on src/main/java/com/devtraces/arterest/domain/UserEntity.java
> +    private String password; //암호화 팔요.
그리고 // 사용시 한 칸 띄고 사용하기로 했던 것 같아요! 이부분도 참고해주시면 좋을 것 같습니다 :)

2023-02-06 04:01 UTC, gwakjaeha reviewed
저도 앞서 두 분이 코멘트 주신 부분들에 대해 동의합니다!

2023-02-06 04:14 UTC, DongvinPark commented on build.gradle
> +	runtimeOnly 'com.h2database:h2'
이 부분도 삭제하겠습니다.

2023-02-06 04:14 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/Feed.java
> +    private UserEntity userEntity;
피드 : 댓글
댓글 : 대댓글
간의 1:N 매핑도 셋팅해보고 문제 생기거나 안 될 경우 공유하겠습니다.

2023-02-06 04:16 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/UserEntity.java
> +public class UserEntity extends BaseEntity {
Mysql에서 테스트 해보고 안 될 경우 결과 공유하겠습니다.

2023-02-06 04:16 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/UserEntity.java
> +    private String password; //암호화 팔요.
회의 전에 작성한 부분이라서 수정이 안 됐네요. 수정하겠습니다.

2023-02-06 04:16 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/Reply.java
> +    private UserEntity user;
유저 엔티티에서 얻을 수 있는 필드는 빼는 방향으로 처리하겠습니다.

그리고
피드 : 댓글
댓글 : 대댓글
간의 1:N 매핑도 셋팅해보고 문제 생기거나 안 될 경우 공유하겠습니다.

2023-02-06 04:17 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/Rereply.java
> +@AllArgsConstructor
수정 전용 메서드를 별도로 작성하는 것으로 바꾸겠습니다 :)

2023-02-07 02:12 UTC, heyazoo1007 reviewed
코드 잘 보았습니다 동빈님! 코드는 잘 수정된 것 같아요. 궁금한 점 하나 댓글 달아놨으니 확인해주시면 감사하겠습니다 :)

2023-02-07 02:12 UTC, heyazoo1007 commented on src/main/java/com/devtraces/arterest/domain/user/User.java
> +    private Set<Feed> feedList = new LinkedHashSet<>();
혹시 이부분은 ArrayList<>() 가 아닌 LinkedHashSet<>() 으로 하신 이유가 뭔지 알 수 있을까요?

2023-02-07 02:17 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/user/User.java
> +    private Set<Feed> feedList = new LinkedHashSet<>();
그 부분은 ArrayList로 수정하겠습니다. 깜빡하고 넘어갈 뻔했네요 ㄷㄷ

2023-02-07 04:16 UTC, soeunkk reviewed
조금 늦은 피드백 죄송합니다! setter 메소드에 대한 개인적읜 의견 남겼는데, 그 부분 빼고 잘 수정해주신 것 같아요! 수고하셨습니다👍

2023-02-07 04:16 UTC, soeunkk commented on src/main/java/com/devtraces/arterest/domain/reply/Reply.java
> +    public void setContent(String content){ this.content = content; }
이 부분도 엔티티 구현 PR 보다는 추후에 있을 피드백 수정 API 때 올리는 것이 좋을 것 같아요! 
다같이 공통으로 쓸 (=충돌이 발생할) 메소드가 아닌 이상 현재 호출하고 있는 메소드만 만들어주시면 좋을 것 같습니다 : )

그리고 나중에도 setter보다는 의미있는 네이밍(ex. updateContent())을 쓰는 건 어떨까요?
이런 방식을 제안드린 이유는 setter라고 네이밍 한 경우 해당 엔티티의 값들이 언제 어디서 변해야 하는지 코드상으로 명확하게 구분할 수가 없다고 생각했기 때문인데요, 조금 더 범위를 좁혀 기능에 맞는 네이밍을 하면 어떨지 여쭤봅니다ㅎㅎ

2023-02-07 04:16 UTC, soeunkk commented on src/main/java/com/devtraces/arterest/domain/rereply/Rereply.java
> +    public void setContent(String content){ this.content = content; }
이 부분도 이하 동문입니다!

2023-02-07 04:16 UTC, soeunkk commented on src/main/java/com/devtraces/arterest/domain/user/User.java
> +    //1:N mapping
사소하지만 주석 사이에 띄어쓰기 해주시면 좋을 것 같아요!ㅎㅎ

2023-02-07 04:16 UTC, soeunkk commented on src/main/java/com/devtraces/arterest/domain/user/User.java
> +
이 부분 역시 사용자 + 계정 API를 맡은 저와 예진님이 작성하도록 하겠습니다. 삭제해주시면 감사하겠습니다!

2023-02-07 04:16 UTC, soeunkk commented on src/main/java/com/devtraces/arterest/domain/feed/Feed.java
> +    public void setHashtags(String hashtags){ this.hashtags = hashtags; }
이 부분도 이하 동문입니다!

2023-02-07 04:20 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/reply/Reply.java
> +    public void setContent(String content){ this.content = content; }
어제 댓글 다시 읽어보니 구현할 필요는 없다고 말씀하신 거였네요 :)
그러면 일단 setter 메서드들은 전부 제외시키고 다시 커밋하겠습니다

2023-02-07 04:21 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/user/User.java
> +    //1:N mapping
이상하게 오타들은 꼭 다른 사람이 봐줘야만 발견되는 것 같네요 ㅎㅎ

2023-02-07 04:32 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/feed/Feed.java
> +    public void setHashtags(String hashtags){ this.hashtags = hashtags; }
일단 세터 메서드들은 전부 빼고 다시 커밋하겠습니다 :)

2023-02-07 04:32 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/user/User.java
> +
이 부분도 삭제하겠습니다 ✅

2023-02-07 04:33 UTC, DongvinPark commented on src/main/java/com/devtraces/arterest/domain/rereply/Rereply.java
> +    public void setContent(String content){ this.content = content; }
일단 세터 메서드는 다시 제외시키겠습니다

2023-02-07 04:40 UTC, soeunkk approved these changes
수정해주신 부분 확인하였습니다! 👏👏 이따 회의에서 봬요~!

2023-02-07 05:50 UTC, heyazoo1007 approved these changes
잘 수정된 것 같습니다!

2023-02-07 06:09 UTC, gwakjaeha approved these changes
수정하신 부분 확인하였습니다!

2023-02-07 06:09 UTC, merged